### ISSUE TITLE
Child-Collection

### ISSUE THREAD

**Issue by Detzler** [tzyganu/moduleCreator#10]
Hi,

imagine the following domain:
- ParentModel
- ChildModel
  (1 to n)

There is no method in ParentModel to get all ChildModels, also there is no method in ChildModelCollection to set a ParentModelFilter to get all ChildModels of a specific ParentModel.

**Comment by tzyganu** [comment]
This will be closed for now because the support for this version will end soon.  
The issue was migrated to the new version. https://github.com/tzyganu/UMC1.9/issues/13
