### ISSUE TITLE
Missing Files in 1.6.3

### ISSUE THREAD

**Issue by code-poel** [tzyganu/moduleCreator#11]
Looks like some files were removed that are still required.

https://github.com/tzyganu/moduleCreator/tree/37bfae6d02f63c4618217e714a887930adaef7f2/app/code/community/Ultimate/ModuleCreator/etc/m/app/design/frontend/base/default/layout/namespace_module

Attempting to save a new module results in the following error.

Warning: file_get_contents(/Workspace/magento/app/code/community/Ultimate/ModuleCreator/etc/m/app/design/frontend/base/default/layout/namespace_module/04_subtree.xml): failed to open stream: No such file or directory in /Workspace/magento/app/code/community/Ultimate/ModuleCreator/Model/Module.php on line 824

**Comment by code-poel** [comment]
These are the files referenced in modulecreator.xml that are missing from the repository.

```
<file>
    <name>04_subtree.xml</name>
    <scope>global</scope>
    <depend>
        <use_frontend />
        <has_tree />
    </depend>
</file>
<file>
    <name>05_default_footer.xml</name>
    <depend>
        <frontend_list />
    </depend>
</file>
<file>
    <name>06_list.xml</name>
    <scope>entity</scope>
    <depend>
        <frontend_list />
    </depend>
</file>
<file>
    <name>07_view.xml</name>
    <scope>entity</scope>
    <depend>
        <frontend_view />
    </depend>
</file>
<file>
    <name>08_entity_rss.xml</name>
    <scope>entity</scope>
    <depend>
        <rss />
    </depend>
</file>
<file>
    <name>09_rss_top.xml</name>
    <depend>
        <rss />
    </depend>
</file>
<file>
    <name>10_rss.xml</name>
    <scope>entity</scope>
    <depend>
        <rss />
    </depend>
</file>
<file>
    <name>11_rss_footer.xml</name>
    <depend>
        <rss />
    </depend>
</file>
<file>
    <name>12_relation_product.xml</name>
    <scope>entity</scope>
    <depend>
        <show_on_product />
    </depend>
</file>
<file>
    <name>13_footer.xml</name>
</file>
```

**Comment by tzyganu** [comment]
There were other files missing also. Something got lost in the last commit. Is fixed now.
