### ISSUE TITLE
New module does not create records in the namespace_module_store table.

### ISSUE THREAD

**Issue by code-poel** [tzyganu/moduleCreator#12]
Creation of a new module with a many to many backend table (namespace_module_store table) will not save a record to that table when you create a new entity record through the generated admin grid edit form.  This, in turn, prevents the item from showing up on the frontend as the getCollection method filters by store_id.

Need an option to disable that filter or display a store selection multi-select on the entity edit form in admin.

**Comment by tzyganu** [comment]
Can you send the xml file generated by the module creator and found in var/modulecreator/package by e-mail at ultimate.module.creator@gmail.com. It would help me identify and solve the problem. Also tell me if the error reproduces on an instance with 1 store view or more.

**Comment by tzyganu** [comment]
Solved in version 1.6.3.1
