### ISSUE TITLE
validate missing: name_singular, name_plural allow "_"

### ISSUE THREAD

**Issue by andras74** [tzyganu/moduleCreator#5]
For more details some xml files:

Throw an exception on run:
  http://pastebin.com/q6SGmpbj

Working well:
  http://pastebin.com/2x5QzAjp

(My Magento version: 1.7.0.2)

**Comment by tzyganu** [comment]
Added client side validation. As long as this extension addresses developers I think it's save to assume that the client side validation is enough.
