### ISSUE TITLE
Tab navigation broken

### ISSUE THREAD

**Issue by philwinkle** [tzyganu/moduleCreator#6]
Ajax content is loading into the left tab navigation in System > Module Creator

![Screen Shot 2013-02-25 at 2 35 54 PM](https://f.cloud.github.com/assets/589550/193367/e42d1aca-7f82-11e2-956d-6d65723c9db5.png)

![Screen Shot 2013-02-25 at 2 35 47 PM](https://f.cloud.github.com/assets/589550/193365/d944af88-7f82-11e2-9874-95acd9703b2f.png)

**Comment by tzyganu** [comment]
Can you provide more info on this issue? (Magento version, browser or anything else you might think it's useful).
I'm not able to reproduce it.

**Comment by philwinkle** [comment]
Magento EE 1.12.1

OS:
Distributor ID: Ubuntu
Description: Ubuntu 12.04 LTS
Release: 12.04
Codename: precise

Browser:
Chrome Version 25.0.1364.99

Installed via Modman, cloned from git repo

On Wed, Feb 27, 2013 at 3:05 PM, Marius notifications@github.com wrote:

> Can you provide more info on this issue? (Magento version, browser or
> anything else you might think it's useful).
> I'm not able to reproduce it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tzyganu/moduleCreator/issues/6#issuecomment-14195714
> .

## 

Follow me on Twitter - @philwinkle
Friend me on Facebook - http://www.facebook.com/philwinkle

**Comment by tzyganu** [comment]
Thanks Phillip.
It seams there is a problem when installing via Modman.
This problem does not reproduce when I copy the zip from github over my magento instance, or when installing through Magento connect.
I will investigate.

**Comment by philwinkle** [comment]
Thanks for the update! I'll try a manual checkout.

On Thu, Feb 28, 2013 at 1:13 AM, Marius notifications@github.com wrote:

> Thanks Phillip.
> It seams there is a problem when installing via Modman.
> This problem does not reproduce when I copy the zip from github over my
> magento instance, or when installing through Magento connect.
> I will investigate.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tzyganu/moduleCreator/issues/6#issuecomment-14218676
> .

## 

Follow me on Twitter - @philwinkle
Friend me on Facebook - http://www.facebook.com/philwinkle

**Comment by tzyganu** [comment]
The problem is cause by the fact that "Allow symlinks" is set to 'No'.
'Allow symlinks' 'Yes' is a requirement for using modman.
https://github.com/colinmollenhour/modman#requirements
