### ISSUE TITLE
OCP

### ISSUE THREAD

**Issue by Detzler** [tzyganu/moduleCreator#9]
Hello and thank you for this great Magento-Extension.
I've done some work with it and want to recommend an enhancement:

The classes are missing the open/closed principle.
E.g.: After the first code generation one needs to extend/modify the classes by hand. Later on, one generates the code again and overwrites the previous changes. The manual modifications to the files are gone. One can git-diff them to fix it but it's a enormous time waste.
The solution would be to generate the classes in a seperate directory called "Generated" or something and also create empty classes that extends them. The empty ones are open for modifications to the develoepr, the generated one are open only for class-extension.

Current structure:
app/code/local/NsModule/Block/Entityname/GeneratedClass.php

Recommended structure:
app/code/local/NsModule/Block/Entityname/Generated/A.php
app/code/local/NsModule/Block/Entityname/B.php (extending A.php)

This pattern is also implemented in Doctrine and Typo3-ExtensionBuilder.

By the way: How about code-generation by using a YAML- or XML-file which contains entity information?

**Comment by tzyganu** [comment]
This is not in the scope of the extension. The main purpose of the Module Creator is to 'jump-start' your extension that with your custom entities. If you want you can still use the generated code in the way you describe. Let's take the entity model for example. You have the class in the file Ns/Module/Model/Entity.php (the way the module creator generates it). If you want to make modifications to it without editing the file just create Ns/Module/Model/Entity/Extended.php with the appropriate class name that extends the original model or an other extension that depends on the generated one. And declare the new model in the config.xml file of the generated extension, or the one you create.

The code can be generated through xml file (sort of). Actually each extension you create with the module creator is saved as an xml file in var/modulecreator/package.
